x_mode: 4
y_mode: 4
x_from: 0
x_to: 6.0
y_from: 0.0
y_to: 6.0
dim: 2
X:
  _target_: src.distributions.GridGaussiansSampler
  x_mode: ${samplers.x_mode}
  y_mode: ${samplers.y_mode}
  x_from: ${samplers.x_from}
  x_to: ${samplers.x_to}
  y_from: ${samplers.y_from}
  y_to: ${samplers.y_to}
  dim: ${samplers.dim}
Y:
  _target_: src.distributions.GridGaussiansSampler
  x_mode: ${samplers.x_mode}
  y_mode: ${samplers.y_mode}
  x_from: ${samplers.x_from}
  x_to: ${samplers.x_to}
  y_from: ${samplers.y_from}
  y_to: ${samplers.y_to}
  dim: ${samplers.dim}
