defaults:
  - _self_
  - experiment_params: default
  - train_params: grid_gaussians
  - model: grid_gaussians
  - samplers: grid_gaussians
  - optimizer: adam
  - plan_sampler: ot
  - hydra: default

name: Grid_Gaussians
