defaults:
  - _self_
  - experiment_params: default
  - train_params: swiss_roll
  - model: swiss_roll
  - samplers: swiss_roll
  - optimizer: adam
  - plan_sampler: ot
  - hydra: default

name: Swiss_Roll
